export const teamNames: string[] = [
  "JUDEUZINHOS",
  "ESTUDADOS",
  "ALEMÃES",
  "OS BORA BIL",
  "TRIBO DO GAU",
  "ROBINHOS",
  "PETISTAS",
  "MITOS",
  "BIXINHAS",
  "PCDS",
  "OBESOS",
  "OS PICA FINA",
  "FEIURINHAS",
  "YODINHAS",
  "BAIANOS",
];
